### PR TITLE
Removed message, causes crash.

### PR DESCRIPTION
**Pull request by SirGamer**
No need for a message there.

### CODE REVIEW

**Comment by ZINGDING** [comment]
Why? I add //.

**Comment by SirGamer** [comment]
Yes, but this is the plugin.yml, not in the code...

**Comment by SirGamer** [comment]
`

**Comment by ZINGDING** [comment]
Haa.... I make mistake....Sorry<

**Comment by SirGamer** [comment]
It's okay. :)

**Comment by SirGamer** [comment]
I have to sleep now, good night!

**Comment by ZINGDING** [comment]
Good night~! Please meet morning~ :)

**Comment by SirGamer** [comment]
Kk.

**Pull request merged**
