### PR TITLE
Sets the cookie into the user's hand.

### PR DESCRIPTION
**Pull request by SirGamer**
(Sets the cookie into the first slot in the hotbar.)

### CODE REVIEW

**Comment by SirGamer** [comment]
Merge this?

**Comment by ZINGDING** [comment]
No! This Pull Request has conflicts that must be resolved

**Comment by SirGamer** [comment]
.-., That has NOTHING to do with the code...

**Comment by SirGamer** [comment]
Closed + removed, making a separate pr.

**Pull request closed without merging**
